In [ ]:
iris 데이터 및 scikit learn logistic regression을 이용하여

붓꽃의 3가지 종류를 구분하는 multinomial classification을 구현할 것.

 

- one-vs-all, one-vs-one 두가지 방법을 사용할 것.

- performance measure는 accuracy를 사용할 것.

- one-vs-one을 구현할때, 데이터에서 두개의 클래스에서 해당되지 않는 레이블의 데이터는 필터링해서 하여야 함.

- training/test 데이터를 7:3으로 split 하는 방법과 k-fold 방식으로 성능평가하는 방식. 두가지를 해볼 것.

- 데이터를 split할 때, 한쪽으로 데이터의 레이블이 쏠리지 않도록 shuffle 할것.





In [198]:
#one-vs-one

def kfold(X,y,idx):
    
    global checklabel
    X,y,idx=shuffle(X,y,idx)
    result=0
    
    KFold(n_splits=5, random_state=42, shuffle=True)
    for train_index, test_index in kf.split(X):
        
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        idx_transfered=idx[test_index]

        lr_model = LogisticRegression(random_state=None, solver='liblinear',multi_class='ovr')
        lr_model.fit(X_train,y_train)
        coef=lr_model.coef_
        print(lr_model.coef_,lr_model.intercept_) #가중치,상수

        y_test_pred = lr_model.predict(X_test)
        for j in range(len(y_test_pred)):
            temp=0
            if y_test_pred[j]=="versicolor":
                temp=1
            elif y_test_pred[j]=="virginica":
                temp=2
            checklabel[idx_transfered[j][0]][temp]+=1
                
        temp=accuracy_score(y_test,y_test_pred)
        print("accuracy for each kfold : ", temp)
        result+=temp
    
    print("\naccuracy for one class : ",result/5,"\n\n")
    
    

In [257]:
import numpy as np
from sklearn import linear_model
from sklearn.utils import shuffle
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import operator

file='/Users/Desktop/iris.csv'
data=pd.read_csv(file)

checklabel=[[int(0)]*3 for i in range(150)]


type1=np.array(data.iloc[:50,0:4])
label1=np.array(data.iloc[:50,4])
type2=np.array(data.iloc[50:100,0:4])
label2=np.array(data.iloc[50:100,4])
type3=np.array(data.iloc[100:150,0:4])
label3=np.array(data.iloc[100:150,4])

idx1=[[i] for i in range(50)]
idx2=[[i] for i in range(50,100)]
idx3=[[i] for i in range(100,150)]

X=np.concatenate((type1,type2),axis=0)
y=np.concatenate((label1,label2),axis=0)
kfold(X,y,np.concatenate((idx1,idx2),axis=0))

X=np.concatenate((type1,type3),axis=0)
y=np.concatenate((label1,label3),axis=0)
kfold(X,y,np.concatenate((idx1,idx3),axis=0))
    
X=np.concatenate((type2,type3),axis=0)
y=np.concatenate((label2,label3),axis=0)
kfold(X,y,np.concatenate((idx2,idx3),axis=0))

resultidx=[]
for i in checklabel:
    temp, value = max(enumerate(i), key=operator.itemgetter(1))
    if str(temp)=="0":
        resultidx.append("setosa")
    elif str(temp)=="1":
        resultidx.append("versicolor")
    else:
        resultidx.append("virginica")

temp=accuracy_score(resultidx,data.iloc[:,4])
print("one-vs-one accuracy : ", temp)

[[-0.35788387 -1.42827745  2.11778591  0.91931326]] [-0.23994223]
accuracy for each kfold :  1.0
[[-0.39167751 -1.37796341  2.13291582  0.96349893]] [-0.25390818]
accuracy for each kfold :  1.0
[[-0.39174825 -1.38953323  2.13187036  0.95606276]] [-0.26260154]
accuracy for each kfold :  1.0
[[-0.38440996 -1.3816851   2.12237857  0.96636637]] [-0.24255576]
accuracy for each kfold :  1.0
[[-0.38133985 -1.37942536  2.12918813  0.92584223]] [-0.23295738]
accuracy for each kfold :  1.0

accuracy for one class :  1.0 


[[-0.54170053 -1.08568302  1.77298031  0.90310066]] [-0.29010974]
accuracy for each kfold :  1.0
[[-0.51380246 -1.13460528  1.73306736  0.92857349]] [-0.27140644]
accuracy for each kfold :  1.0
[[-0.53746208 -1.11606751  1.73025413  0.88651884]] [-0.29578337]
accuracy for each kfold :  1.0
[[-0.53896718 -1.11421245  1.75797687  0.90419154]] [-0.28574919]
accuracy for each kfold :  1.0
[[-0.52301452 -1.09479755  1.73635579  0.8884224 ]] [-0.27988294]
accuracy for each kfold :  

In [218]:
#one-vs-one

def split(X,y,idx):
    result=0
    for trial in range(5):
        global checklabel
        X,y,idx=shuffle(X,y,idx)

        X_train, X_test, y_train, y_test, idx_temp, idx_transfered = train_test_split(X, y,idx, test_size=0.3, random_state=42)

        lr_model = LogisticRegression(random_state=None, solver='liblinear',multi_class='ovr')
        lr_model.fit(X_train,y_train)
        coef=lr_model.coef_
        print(lr_model.coef_,lr_model.intercept_) #가중치,상수

        y_test_pred = lr_model.predict(X_test)
        for j in range(len(y_test_pred)):
            temp=0
            if y_test_pred[j]=="versicolor":
                 temp=1
            elif y_test_pred[j]=="virginica":
                 temp=2
            checklabel[idx_transfered[j][0]][temp]+=1
    
        temp=accuracy_score(y_test,y_test_pred)
        print("accuracy for each trial : ", temp)
        result+=temp
    
    print("\naccuracy for one class : ",result/5,"\n\n")
    

    
    

In [256]:
import numpy as np
from sklearn import linear_model
from sklearn.utils import shuffle
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import operator

file='/Users/Desktop/iris.csv'
data=pd.read_csv(file)

checklabel=[[int(0)]*3 for i in range(150)]


type1=np.array(data.iloc[:50,0:4])
label1=np.array(data.iloc[:50,4])
type2=np.array(data.iloc[50:100,0:4])
label2=np.array(data.iloc[50:100,4])
type3=np.array(data.iloc[100:150,0:4])
label3=np.array(data.iloc[100:150,4])

idx1=[[i] for i in range(50)]
idx2=[[i] for i in range(50,100)]
idx3=[[i] for i in range(100,150)]

X=np.concatenate((type1,type2),axis=0)
y=np.concatenate((label1,label2),axis=0)
split(X,y,np.concatenate((idx1,idx2),axis=0))

X=np.concatenate((type1,type3),axis=0)
y=np.concatenate((label1,label3),axis=0)
split(X,y,np.concatenate((idx1,idx3),axis=0))
    
X=np.concatenate((type2,type3),axis=0)
y=np.concatenate((label2,label3),axis=0)
split(X,y,np.concatenate((idx2,idx3),axis=0))


resultidx=[]
for i in checklabel:
    temp, value = max(enumerate(i), key=operator.itemgetter(1))
    if str(temp)=="0":
        resultidx.append("setosa")
    elif str(temp)=="1":
        resultidx.append("versicolor")
    else:
        resultidx.append("virginica")


temp=accuracy_score(resultidx,data.iloc[:,4])
print("one-vs-one accuracy : ", temp)


[[-0.3903948  -1.36368755  2.0614069   0.90103182]] [-0.24083145]
accuracy for each trial :  1.0
[[-0.36212407 -1.3563174   2.07440213  0.92512505]] [-0.24282948]
accuracy for each trial :  1.0
[[-0.36193519 -1.34842892  2.0772765   0.91426932]] [-0.23015344]
accuracy for each trial :  1.0
[[-0.33916736 -1.31992913  2.06190718  0.89462786]] [-0.23674589]
accuracy for each trial :  1.0
[[-0.37262451 -1.3266087   2.0859366   0.91038419]] [-0.259211]
accuracy for each trial :  1.0

accuracy for one class :  1.0 


[[-0.51997378 -1.07407739  1.69657478  0.90271749]] [-0.27000796]
accuracy for each trial :  1.0
[[-0.52109152 -1.08105615  1.71655258  0.88160236]] [-0.2807216]
accuracy for each trial :  1.0
[[-0.53496455 -1.06938251  1.70156063  0.88743694]] [-0.28053818]
accuracy for each trial :  1.0
[[-0.50858176 -1.08541976  1.68074924  0.874315  ]] [-0.28045455]
accuracy for each trial :  1.0
[[-0.52641727 -1.05841579  1.71400928  0.85009734]] [-0.27980619]
accuracy for each trial :  1.0

In [358]:
#one-vs-rest

def kfold(X,y,idx, _class):
    result=0
    global checklabel
    X,y,idx=shuffle(X,y,idx)

    KFold(n_splits=5, random_state=42, shuffle=True)
    for train_index, test_index in kf.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        idx_transfered=idx[test_index]

        lr_model = LogisticRegression(random_state=None, solver='liblinear',multi_class='ovr')
        lr_model.fit(X_train,y_train)
        coef=lr_model.coef_
        print(lr_model.coef_,lr_model.intercept_) #가중치,상수
        
        for i in range(len(X_test)):
            temp=coef*X_test[i]
            temp_sum=[sum(j) for j in temp][0] + lr_model.intercept_
            temp=1 / (1 + np.exp(-1*temp_sum))
            checklabel[idx_transfered[i]][_class]+=temp[0]
        
        y_test_pred = lr_model.predict(X_test)
        temp=accuracy_score(y_test,y_test_pred)
        print("accuracy for each trial : ", temp)
        result+=temp
    
    print("\naccuracy for one class : ",result/5,"\n\n")

    
    

In [366]:
import numpy as np
from sklearn import linear_model
from sklearn.utils import shuffle
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import operator

file='/Users/Desktop/iris.csv'
data=pd.read_csv(file)

checklabel=[[int(0)]*3 for i in range(150)]

label1=np.array(data.iloc[:50,4])
label2=np.array(data.iloc[50:100,4])
label3=np.array(data.iloc[100:150,4])

temp=['other' for i in range(50)]
X=np.array(data.iloc[:,0:4])
idx=np.array([i for i in range(150)])

y=np.concatenate((label1,temp),axis=0)
y=np.concatenate((y,temp),axis=0)
kfold(X,y,idx,0)

y=np.concatenate((temp,label2),axis=0)
y=np.concatenate((y,temp),axis=0)
kfold(X,y,idx,1)

y=np.concatenate((temp,temp),axis=0)
y=np.concatenate((y,label3),axis=0)
kfold(X,y,idx,2)



resultidx=[]
for i in checklabel:
    temp, value = max(enumerate(i), key=operator.itemgetter(1))
    if str(temp)=="0":
        resultidx.append("setosa")
    elif str(temp)=="1":
        resultidx.append("versicolor")
    else:
        resultidx.append("virginica")


temp=accuracy_score(resultidx,data.iloc[:,4])
print("one-vs-rest accuracy : ", temp)



[[ 0.38828874  1.39362524 -2.15982715 -0.99815336]] [0.25900842]
accuracy for each trial :  1.0
[[ 0.41545845  1.36363506 -2.15814847 -0.9438865 ]] [0.27245649]
accuracy for each trial :  1.0
[[ 0.37379746  1.41000138 -2.13438302 -0.94208647]] [0.24114688]
accuracy for each trial :  1.0
[[ 0.39882549  1.38522982 -2.16946528 -0.99048565]] [0.2621625]
accuracy for each trial :  1.0
[[ 0.37445601  1.40805798 -2.13880573 -0.97325501]] [0.22635373]
accuracy for each trial :  1.0

accuracy for one class :  1.0 


[[ 0.4921568  -1.62737192  0.43930187 -1.12405033]] [0.87314202]
accuracy for each trial :  0.6
[[ 0.41385701 -1.56656798  0.49228642 -1.17758135]] [1.04307683]
accuracy for each trial :  0.7
[[ 0.4133476  -1.48147096  0.46564026 -1.08761192]] [0.85001479]
accuracy for each trial :  0.7333333333333333
[[ 0.45008479 -1.55949391  0.65303097 -1.55835497]] [0.78693698]
accuracy for each trial :  0.7
[[ 0.27800494 -1.33529842  0.61651419 -1.38977136]] [0.95431394]
accuracy for each trial

In [ ]:
y=np.concatenate((label1,temp),axis=0)
y=np.concatenate((y,temp),axis=0)
kfold(X,y,idx,0)

y=np.concatenate((temp,label2),axis=0)
y=np.concatenate((y,temp),axis=0)
kfold(X,y,idx,1)

y=np.concatenate((temp,temp),axis=0)
y=np.concatenate((y,label3),axis=0)
kfold(X,y,idx,2)


In [368]:
#one-vs-rest

def split(X,y,idx, _class):
    result=0
    for trial in range(5):
        global checklabel
        X,y,idx=shuffle(X,y,idx)

        X_train, X_test, y_train, y_test, idx_temp, idx_transfered = train_test_split(X, y,idx, test_size=0.3, random_state=42)

        lr_model = LogisticRegression(random_state=None, solver='liblinear',multi_class='ovr')
        lr_model.fit(X_train,y_train)
        coef=lr_model.coef_
        print(lr_model.coef_,lr_model.intercept_) #가중치,상수
        
        
        for i in range(len(X_test)):
            temp=coef*X_test[i]
            temp_sum=[sum(j) for j in temp][0] + lr_model.intercept_
            temp=1 / (1 + np.exp(-1*temp_sum))
            checklabel[idx_transfered[i]][_class]+=temp[0]
        
        y_test_pred = lr_model.predict(X_test)
        temp=accuracy_score(y_test,y_test_pred)
        print("accuracy for each trial : ", temp)
        result+=temp
    
    print("\naccuracy for one class : ",result/5,"\n\n")

    
    

In [369]:
import numpy as np
from sklearn import linear_model
from sklearn.utils import shuffle
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import operator

file='/Users/Desktop/iris.csv'
data=pd.read_csv(file)

checklabel=[[int(0)]*3 for i in range(150)]

label1=np.array(data.iloc[:50,4])
label2=np.array(data.iloc[50:100,4])
label3=np.array(data.iloc[100:150,4])

temp=['other' for i in range(50)]
X=np.array(data.iloc[:,0:4])
idx=[i for i in range(150)]

y=np.concatenate((label1,temp),axis=0)
y=np.concatenate((y,temp),axis=0)
split(X,y,idx,0)

y=np.concatenate((temp,label2),axis=0)
y=np.concatenate((y,temp),axis=0)
split(X,y,idx,1)

y=np.concatenate((temp,temp),axis=0)
y=np.concatenate((y,label3),axis=0)
split(X,y,idx,2)

resultidx=[]
for i in checklabel:
    temp, value = max(enumerate(i), key=operator.itemgetter(1))
    if str(temp)=="0":
        resultidx.append("setosa")
    elif str(temp)=="1":
        resultidx.append("versicolor")
    else:
        resultidx.append("virginica")


temp=accuracy_score(resultidx,data.iloc[:,4])
print("one-vs-rest accuracy : ", temp)



[[ 0.39040984  1.31863539 -2.10018047 -1.00742837]] [0.26907204]
accuracy for each trial :  1.0
[[ 0.41724319  1.31227756 -2.10294705 -0.89687967]] [0.25488071]
accuracy for each trial :  1.0
[[ 0.39222551  1.33211087 -2.10540691 -0.92206721]] [0.24095329]
accuracy for each trial :  1.0
[[ 0.39441051  1.29378653 -2.08259323 -0.93610133]] [0.27043254]
accuracy for each trial :  1.0
[[ 0.3814485   1.31998544 -2.07987814 -0.92587839]] [0.23372492]
accuracy for each trial :  1.0

accuracy for one class :  1.0 


[[ 0.45372857 -1.62745299  0.6177927  -1.49236794]] [0.93972541]
accuracy for each trial :  0.6666666666666666
[[ 0.62732372 -1.83465175  0.38091822 -1.15251286]] [0.81967802]
accuracy for each trial :  0.5777777777777777
[[ 0.33676401 -1.36433687  0.34696146 -0.80085144]] [0.98249772]
accuracy for each trial :  0.6666666666666666
[[ 0.38795468 -1.49695531  0.69919215 -1.51605022]] [0.78097167]
accuracy for each trial :  0.6888888888888889
[[ 0.29485527 -1.36787278  0.58121914 -1.1